import createBigImage from "./createBigImage";
import createHomeContentBody from "./createHomeContentBody";
import image from "./pizzeriaImage.jpeg";

export default function createHomePage() {
    const parentNode = document.querySelector("#content");

    const bigImage = createBigImage({image, alt: "a violet pizzeria with fake branding generated by Google Gemini 2.0"})
    const contentBodyWrapper = createHomeContentBody();

    parentNode.appendChild(bigImage);
    parentNode.appendChild(contentBodyWrapper);
}