import createBigImage from "./createBigImage";
import image from "./pizzeriaImage.jpeg";
import paraBuilder from "./paraBuilder";

export default function createHomePage() {
    const parentNode = document.querySelector("#content");
    const bigImage = createBigImage({image, alt: "a violet pizzeria with fake branding generated by Google Gemini 2.0"});
    const heading = document.createElement("h1");
    const homePageContentNode = document.createElement("div");
    const restaurantDescription = paraBuilder("Lorem ipsum dolor sit amet consectetur adipisicing elit." 
        + "Id nulla ea voluptates laborum eaque esse, voluptatibus numquam, quia," 
        + "fuga delectus quas. Reiciendis nihil labore accusantium modi quibusdam at! Sint. lorem lorem");
    
    heading.innerText = "The Restaurant For The Ages";
    homePageContentNode.appendChild(heading);
    homePageContentNode.appendChild(restaurantDescription);
    
    homePageContentNode.classList.add("content-body");

    parentNode.appendChild(bigImage);
    parentNode.appendChild(homePageContentNode);
}