import image from "./pizzaToss.jpg";
import createBigImage from "./createBigImage";
export default function createAboutPage() {
    const parentNode = document.querySelector("#content");
    const bigImage = createBigImage({image, alt: "a violet pizzeria with fake branding generated by Google Gemini 2.0"})

    const heading = document.createElement("h1");
    heading.innerText = "Established since 1985";

    const paraBuilder = (text) => {
        const paragraph = document.createElement("p");
        paragraph.innerText = text;
        return paragraph;
    }

    const paraOne = paraBuilder("Since 1985, Abhi's Pizzeria has been a cornerstone of Kelowna's culinary scene." +
         " Our unique blend of Indian and Italian cuisine has delighted taste buds and created unforgettable dining experiences." +
         " From the moment you step through our doors, you'll be transported to a world of bold flavors and aromatic delights.");

    const paraTwo = paraBuilder("The menu is a delightful fusion of two culinary worlds, offering a tantalizing array of dishes that blend tradition with innovation."
         + " From crispy naan pizzas topped with aromatic Indian spices to creamy masala pastas infused with" 
         + "exotic flavors, every dish is a testament to the chef's culinary artistry."
         + " The restaurant's signature dish, the \"Tandoori Margherita,\" is a masterpiece that combines the smoky flavors of tandoori"
         + "oven with the classic simplicity of a Margherita pizza.");

    const paraThree = paraBuilder("Join us at Abhi's Pizzeria and embark on a culinary adventure that will leave you craving more.")
    
    const aboutPageContentNode = document.createElement("div");
    aboutPageContentNode.appendChild(heading);
    aboutPageContentNode.appendChild(paraOne);
    aboutPageContentNode.appendChild(paraTwo);
    aboutPageContentNode.appendChild(paraThree);

    aboutPageContentNode.classList.add("content-body");
    
    parentNode.appendChild(bigImage);
    parentNode.appendChild(aboutPageContentNode);
}