import "./style.css";
/*
    <div class="main-image">
        <img src="./pizzeriaImage.jpeg" width="600px" height="800px" alt="a violet pizzeria with fake branding generated by Google Gemini 2.0">
    </div>
    <div class="content-body">
        <h1>The Restaurant</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Id nulla ea voluptates laborum eaque esse, voluptatibus numquam, quia,
        fuga delectus quas. Error reiciendis nihil labore accusantium modi quibusdam at! Sint.
        </p>
    </div>
*/
import createBigImage from "./createBigImage.js";
import image from "./pizzeriaImage.jpeg";

const parentNode = document.querySelector("#content");
const bigImageWrapperNode = createBigImage({image: image, alt: "a violet pizzeria with fake branding generated by Google Gemini 2.0"})
console.log(bigImageWrapperNode.innerHTML);
parentNode.appendChild(bigImageWrapperNode);
